<div style="text-align: center;">
  <img src="https://github.com/Hack-io-Data/Imagenes/blob/main/01-LogosHackio/logo_naranja@4x.png?raw=true" alt="esquema" />
</div>

In [2]:
import os

In [4]:
datos = os.listdir()
datos

['laboratorio-modulo2-leccion01-numpy.ipynb',
 'laboratorio-modulo2-leccion05-limpieza.ipynb',
 'laboratorio-modulo2-leccion04-visualizacion.ipynb',
 'laboratorio-modulo2-leccion03-groupby.ipynb',
 'laboratorio-modulo2-leccion02-eda-union.ipynb',
 'laboratorio-modulo2-leccion03-filtrado.ipynb']

In [ ]:
diccioanrio_df = {diccioanrio_df[re.findall("\d{4}", i)[0]] : pd.read_csv(f"..dato/{i}") for i in datos}

diccioanrio_df = {}
for i in datos:
    df = pd.read_csv(i)
    diccioanrio_df[i.spl]


for i in datos
# Laboratorio de NumPy

#### Ejercicio 1 - Crea un array de 1D con los números del 0 al 9.

In [3]:
import numpy as np

In [8]:
lista = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
array1 = np.array(lista)
print(array1)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
array1.size
array1.dtype

dtype('int64')

#### Ejercicio 2 - Convierte un array 1D en un array 2D con 2 filas y 5 columnas.

In [10]:
array1d = np.arange(10)
array1d
array1d.size
array1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## ¿por que es diferente arriba y abajo?


In [11]:
reshaped_a = np.reshape(array1, (2, 5))
reshaped_a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### Ejercicio 3 - Encuentra los índices de los elementos con valor distinto de 0 en el siguiente array: [0, 2, 0, 3, 0, 4, 0].

In [ ]:
lista2 = [0, 2, 0, 3, 0, 4, 0]
array_ceros = np.array(lista2)

array_ceros[:2]

#no se hacerlo 

array([0, 2])

#### Ejercicio 4 - Crea un array 3x3 con valores aleatorios entre 0 y 1.

In [19]:
np.random.rand(3,3)

array([[0.60890539, 0.18874082, 0.94243315],
       [0.37211477, 0.6355751 , 0.88791739],
       [0.46543737, 0.20480193, 0.82837769]])

#### Ejercicio 5 - Crea un array de 10 números aleatorios y encuentra el valor máximo y mínimo.

In [29]:
array3 = np.random.randint(3, 110, (4, 4))
array3

array([[ 66,  38,  50,  77],
       [ 62,  91,  62,  71],
       [ 94,  50,  53,  72],
       [ 71,  59, 100,  17]], dtype=int32)

In [31]:
np.max(array3)

np.int32(100)

In [32]:
np.min(array3)

np.int32(17)

#### Ejercicio 6 - Crea un array de una dimensión e inviértelo. 


#### Ejercicio 6 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Selecciona el primer `15` del array.

- Selecciona todos los elementos del primer array. 

- Selecciona la última fila del último array


In [34]:
array5 = np.random.randint(1, 24, (2, 3, 4))
array5

array([[[ 6,  9, 13,  6],
        [ 3,  5,  8, 12],
        [ 5, 13, 19,  1]],

       [[15, 18,  1, 16],
        [ 1, 14,  7, 14],
        [ 1, 14, 23,  3]]], dtype=int32)

In [35]:
array5[1, 0, 0]

np.int32(15)

In [36]:
array5[0, :]

array([[ 6,  9, 13,  6],
       [ 3,  5,  8, 12],
       [ 5, 13, 19,  1]], dtype=int32)

In [37]:
array5[1, 2:]

array([[ 1, 14, 23,  3]], dtype=int32)


#### Ejercicio 7 - Genera un array tridimensional de dimensiones (3, 2, 5) con valores enteros del 1 al 30.

- Selecciona el subarray que contiene los dos primeros elementos de cada fila del primer array.

- Selecciona el subarray que contiene todas las filas de los dos últimos arrays.


In [39]:
array6 = np.random.randint(1, 30, (3, 2, 5))
array6

array([[[27,  7, 20,  5, 29],
        [11,  9,  8,  3, 26]],

       [[21,  5, 11, 20,  2],
        [12,  9,  4, 23,  7]],

       [[19, 27, 17,  6, 16],
        [17, 12, 28, 23, 29]]], dtype=int32)

In [55]:
sub_array1 = array6[0, :, :2]
sub_array1

array([[27,  7],
       [11,  9]], dtype=int32)

In [57]:
sub_array2 = array6[1:, :, :]
sub_array2

array([[[21,  5, 11, 20,  2],
        [12,  9,  4, 23,  7]],

       [[19, 27, 17,  6, 16],
        [17, 12, 28, 23, 29]]], dtype=int32)

#### Ejercicio 8 - Genera un array tridimensional de dimensiones (4, 3, 2) con valores enteros del 1 al 24.

- Cambia todos los elementos de la segunda fila del segundo array por `0`.

- Cambia todos los valores del último array a `-1`.


In [41]:
array7 = np.random.randint(1, 24, (4, 3, 2))
array7

array([[[ 4, 18],
        [15, 21],
        [18,  4]],

       [[ 2,  8],
        [21,  6],
        [10, 21]],

       [[21,  6],
        [19, 21],
        [ 6, 15]],

       [[11, 14],
        [ 4,  1],
        [13,  5]]], dtype=int32)

In [46]:
array7[1, 1, :] = 0
array7

array([[[ 4, 18],
        [15, 21],
        [18,  4]],

       [[ 2,  8],
        [ 0,  0],
        [10, 21]],

       [[21,  6],
        [19, 21],
        [ 6, 15]],

       [[11, 14],
        [ 4,  1],
        [13,  5]]], dtype=int32)

In [47]:
array7[3,:,:] = -1
array7

array([[[ 4, 18],
        [15, 21],
        [18,  4]],

       [[ 2,  8],
        [ 0,  0],
        [10, 21]],

       [[21,  6],
        [19, 21],
        [ 6, 15]],

       [[-1, -1],
        [-1, -1],
        [-1, -1]]], dtype=int32)


#### Ejercicio 9 - Genera un array tridimensional de dimensiones (2, 4, 3) con valores enteros del -10 al 13.

- Selecciona todos los elementos mayores a `5`.

- Reemplaza todos los elementos negativos por `0`.


In [61]:
array9 = np.random.randint(-10, 13, (2, 4, 3))
array9


array([[[  7,  -6,   5],
        [ -8,  10,   3],
        [ 10,   3,  -9],
        [ 12,  -1, -10]],

       [[ -1,   4,  -8],
        [ -1,   4,   7],
        [  5,  -1,  12],
        [ -4,   5,  -8]]], dtype=int32)

In [67]:
array01 = array9[array9 > 5]
array01

array([ 7, 10, 10, 12,  7, 12], dtype=int32)

In [70]:
array9[array9 < 0] = 0
array9

array([[[ 7,  0,  5],
        [ 0, 10,  3],
        [10,  3,  0],
        [12,  0,  0]],

       [[ 0,  4,  0],
        [ 0,  4,  7],
        [ 5,  0, 12],
        [ 0,  5,  0]]], dtype=int32)

#### Ejercicio 10 - Genera un array tridimensional de dimensiones (3, 3, 3) con valores enteros del 1 al 27.

- Selecciona el subarray del segundo array que contenga solo las dos primeras columnas.

- Selecciona todos los elementos del tercer array que sean mayores que `20`.


In [84]:
array10 = np.random.randint(1, 27, (3, 3, 3))
array10

array([[[23, 21, 12],
        [19, 24, 10],
        [ 9, 17, 15]],

       [[16, 11, 26],
        [20,  3, 17],
        [16, 19, 22]],

       [[26,  3, 21],
        [12, 19,  4],
        [20, 16,  3]]], dtype=int32)

In [88]:
subbarray99 = array10[1, :, :2]
subbarray99

array([[16, 11],
       [20,  3],
       [16, 19]], dtype=int32)

#### Ejercicio 11 - Crea un array de 10 números aleatorios y reemplaza los valores máximos y mínimos por 0.

In [97]:
array11 = np.random.randint(1, 101, size= 10)
array11

array([62, 24, 99, 64,  9, 26, 40, 37, 80, 36], dtype=int32)

In [105]:
array11[array11 == array11.max()] = 0
array11[array11== array11.min()] = 0
array11

array([62, 24,  0, 64,  9, 26, 40, 37, 80, 36], dtype=int32)

In [99]:
array111 = np.random.randint(1, 191, size=(2, 5))
array111

array([[ 22, 163, 184,  27,   5],
       [ 31,  20,  45, 133, 177]], dtype=int32)

#### Ejercicio 12 - Genera un array de 15 números aleatorios enteros entre 1 y 100 y reordénalo en orden ascendente.

In [109]:
array12 = np.random.randint(1, 100, size=15)
np.sort(array12)

array([ 1,  2,  4, 10, 12, 20, 26, 45, 57, 67, 73, 77, 78, 80, 82],
      dtype=int32)

#### Ejercicio 11 - Calcula la suma de los elementos a lo largo de las filas y columnas en una matriz 4x4.

In [111]:
array11a = np.random.randint(1, 54, (4, 4))
array11a

array([[10, 53, 11, 41],
       [36,  6,  4, 28],
       [12, 26, 51, 19],
       [41, 50, 41, 21]], dtype=int32)

In [ ]:
suma_col = np.sum(array11a, axis=0) ##axis 0 = columna
suma_col

array([ 99, 135, 107, 109])

In [114]:
suma_fil = np.sum(array11a, axis =1)
suma_fil

array([115,  74, 108, 153])

#### Ejercicio 12 - Crea una matriz de 5x5 con valores en el borde igual a 1 y en el interior igual a 0.

In [117]:
a12 = np.zeros((5,5))
a12

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [119]:
a12[0, :] = 1
a12[:, 0] = 1
a12[4, :] = 1
a12[:, 4] = 1
a12

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### Ejercicio 13 - Calcula la media y la desviación estándar de un array de 10 números aleatorios.

In [123]:
a13 = np.random.randint(1, 100, size= 10)
media = np.mean(a13)
media

np.float64(37.0)

In [124]:
stdr = np.std(a13)
stdr

np.float64(24.116384471972577)

#### Ejercicio 14 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Transpón el array para intercambiar los ejes de la forma (2, 3, 4) a (4, 3, 2).

- Observa cómo cambian las posiciones de los elementos y sus índices después de la transposición. Explica en una celda de markdown que es lo que ha pasado. 


In [127]:
a14 = np.random.randint(1, 25, (2,3,4))
a14

array([[[23, 12,  5,  2],
        [21, 21, 19, 17],
        [21, 11, 11, 10]],

       [[10, 14,  1, 17],
        [11, 19, 24, 21],
        [24, 18,  6, 17]]], dtype=int32)

In [130]:
a14t = a14.transpose(2, 1, 0)
a14t

array([[[23, 10],
        [21, 11],
        [21, 24]],

       [[12, 14],
        [21, 19],
        [11, 18]],

       [[ 5,  1],
        [19, 24],
        [11,  6]],

       [[ 2, 17],
        [17, 21],
        [10, 17]]], dtype=int32)

#### Ejercicio 15 - Genera un array tridimensional de dimensiones (3, 4, 2) con valores enteros del 1 al 24.

- Transpón el array para intercambiar el primer y segundo eje, de manera que la nueva forma del array sea (4, 3, 2).


#### Ejercicio 16 - Genera un array tridimensional de dimensiones (3, 2, 4) con valores enteros del 1 al 24.

- Realiza una rotación completa de los ejes para convertir la forma original (3, 2, 4) en (4, 3, 2).


#### Ejercicio 17 - Manipulación de Arrays en 3D

- Crea un array tridimensional con dimensiones (3, 4, 5) cuyos elementos sean números enteros aleatorios entre -10 y 10.

- Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Luego, reemplaza los valores de la matriz vacía basada en los valores del primer array bajo las siguientes condiciones:

   - Si el valor es igual a la mediana, se reemplaza por `"M"`.

   - Si el valor es mayor que la mediana, se reemplaza por `"X"`.

   - Si el valor es menor que la mediana, se reemplaza por `"Y"`.

   - Si el valor es igual al máximo, se reemplaza por `"MAX"`.

   - Si el valor es igual al mínimo, se reemplaza por `"MIN"`.


#### Ejercicio 18 - Verificación de Filas y Columnas Iguales

Crea un array bidimensional de dimensiones 4x4, escribe un código para determinar si alguna fila es exactamente igual a alguna columna.

**Reglas:**

- No puedes usar funciones predefinidas de NumPy para comparar filas y columnas (`np.array_equal`, etc.).

- Debes resolverlo con estructuras básicas de Python (bucles, condicionales, etc.).

- Debes revisar si hay al menos una fila que coincida exactamente con alguna columna.

**Pistas**:

- Puedes recorrer cada fila y cada columna de la matriz usando bucles.

- Para comparar una fila con una columna, puedes hacerlo elemento por elemento.